var express = require("express");
var router = express.Router();
var usersController = require("../controllers/usersController");
router.get("/createtable", usersController.createTable);
router.post("/", usersController.insertUsers);
router.get("/", usersController.selectUsers);
router.get("/:id", usersController.viewUser);
router.delete("/:id", usersController.deleteUser);
router.delete("/", usersController.deleteAll);
router.put("/:id", usersController.updateUser);
module.exports = router;
